CREATE USER 'db'@'localhost' IDENTIFIED BY 'db';
CREATE DATABASE `db` DEFAULT CHARACTER SET = `utf8`;
GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, GRANT OPTION, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `db`.* TO 'db'@'localhost';
FLUSH PRIVILEGES;
